### ISSUE TITLE
release v2

### ISSUE THREAD

**Issue by jurgenvinju** [SWAT-engineering/maven-full-artifacts-action#5]
pls release v2; the rascal project needs it in order to skip the duplicate builds and to be able to use the screenshot feature of the tutor without being overwritten.

**Comment by DavyLandman** [comment]
I just released: "v2.0-rc1". If you can verify it works, I can make a new v2 release.

**Comment by jurgenvinju** [comment]
Alas it did not work. Github actions does not support arrays for action parameters. So I rewrote it with a different PR; please have a look? The work on the documentation is hinging on this one. A new RC would be cool then I can test it again. Also, I wonder what you think about the rough "split" method and if we should do better. We might call a JSON parser on the string for example.

**Comment by jurgenvinju** [comment]
Something like:

```
const anExampleVariable = '["-Drascal.compile.skip","-Drascal.tutor.skip"]';
const anArray = ["a", ...JSON.parse(anExampleVariable), "b"];

console.log(anArray)
// [LOG]: ["a", "-Drascal.compile.skip", "-Drascal.tutor.skip", "b"] 
```

**Comment by DavyLandman** [comment]
I've provided an alternative for what other actions are also doing, as this is indeed a missing feature.

**Comment by DavyLandman** [comment]
This has been completed.
